config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  resources :orders

  resources :locations


  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :contacts
  resources :contractors
  resources :cars
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/adv_option.rb
class AdvOption < ApplicationRecord
  has_and_belongs_to_many :orders
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car.rb
class Car < ApplicationRecord
  # has_many :driver_appointments
  # has_many :drivers, :through => :driver_appointments
  # has_one :driver
  validates :name, presence: true

  # rails_admin do
  #   configure :driver do
  #     label 'Водитель: '
  #   end
  # end


end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :contractor
  validates :name, presence: true

  rails_admin do
    configure :contractor do
      label 'Контрагент: '
    end
  end
end

app/models/contractor.rb
class Contractor < ApplicationRecord
  has_many :contacts
end

app/models/driver.rb
class Driver < ApplicationRecord
  # has_many :driver_appointments
  # has_many :cars, :through => :driver_appointments
  # has_one :car

  # rails_admin do
  #   configure :car do
  #     label ': '
  #   end
  # end
end

app/models/location.rb
class Location < ApplicationRecord
  geocoded_by :address       # can also be an IP address
  after_validation :geocode  # auto-fetch coordinates
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :adv_options
  has_many :purposes
  # geocoded_by :full_street_address   # can also be an IP address
  # after_validation :geocode          # auto-fetch coordinates
  #
  #Mounts paperclip image
  has_attached_file :file

  #This validates the type of file uploaded. According to this, only images are allowed.
  # validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
  validates_attachment :file, :content_type => {:content_type => %w(image/jpeg image/jpg image/png application/pdf application/msword application/vnd.openxmlformats-officedocument.wordprocessingml.document)},
                       size: {in: 0..5.megabytes}

end

app/models/purpose.rb
class Purpose < ApplicationRecord
end

app/models/transport_company.rb
class TransportCompany < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :orders
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  def index
    if params[:search].present?
      # @locations = Location.near(params[:search], 50, :order => :distance)
      @locations = Location.near(params[:search], 50)
    else
      @locations = Location.all
    end
  end

  def show
    @location = Location.find(params[:id])
  end

  def new
    @location = Location.new
  end

  def create
    @location = Location.new(allowed_params)
    if @location.save
      redirect_to @location, :notice => "Successfully created location."
    else
      render :new
    end
  end

  def edit
    @location = Location.find(params[:id])
  end

  def update
    @location = Location.find(params[:id])
    if @location.update_attributes(allowed_params)
      redirect_to @location, :notice  => "Successfully updated location."
    else
      render :edit
    end
  end

  def destroy
    @location = Location.find(params[:id])
    @location.destroy

    redirect_to locations_url, :notice => "Successfully destroyed location."
  end

  private

  def allowed_params
    params.require(:location).permit(:id, :address, :latitude, :longitude)
  end
end

app/controllers/order_controller.rb
class OrderController < ApplicationController
  def new
  end

  def list
  end

  def delete
  end

  def update
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    # @orders = Order.all
    # @orders = Order.paginate(page: params[:page], per_page: 2)
    @orders = Order.where(user_id: current_user).paginate(page: params[:page], per_page: 2)

  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)
    @order.user = current_user

    respond_to do |format|
      if @order.save
        flash[:notice] = 'Order was successfully created!'
        format.html {redirect_to @order, notice: 'Order was successfully created.'}
        format.json {render :show, status: :created, location: @order}
        # redirect_to root_path
      else
        flash[:alert] = 'Order was not created!'
        format.html {render :new}
        format.json {render json: @order.errors, status: :unprocessable_entity}
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html {redirect_to @order, notice: 'Order was successfully updated.'}
        format.json {render :show, status: :ok, location: @order}
      else
        format.html {render :edit}
        format.json {render json: @order.errors, status: :unprocessable_entity}
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html {redirect_to orders_url, notice: 'Order was successfully destroyed.'}
      format.json {head :no_content}
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_order
    @order = Order.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def order_params
    params.require(:order).permit(:comment, :address, :start_date, :end_date, :dover, :parking, :heat, :wepay, :big, :sum,:file,)
    # params.fetch(:order,:comment,:address,:start_date,:end_date,:dover,:parking,:heat,:wepay,:big, :sum, {})
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  def index
    @order = Order.new
  end

  def about
    redirect_to "/orders/new"
    # @order = Order.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper


end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/contractors_helper.rb
module ContractorsHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/order/delete.html.erb
<h1>Order#delete</h1>
<p>Find me in app/views/order/delete.html.erb</p>

app/views/order/list.html.erb
<h1>Order#list</h1>
<p>Find me in app/views/order/list.html.erb</p>

app/views/order/new.html.erb
<h1>Order#new</h1>
<p>Find me in app/views/order/new.html.erb</p>

app/views/order/update.html.erb
<h1>Order#update</h1>
<p>Find me in app/views/order/update.html.erb</p>

app/views/orders/_form.html.erb
<%= render 'common/order_form'%>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%#= render 'form', order: @order %>
<%#= render 'common/order_form' %>
<%= render :partial => 'common/order_form' %>
<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<h2>Список заказов:</h2>



<div class="container-fluid">
  <div class="row row-fluid justify-content-md-center">

    <%#= will_paginate %>

    <div class="table-responsive span11">
      <table class="table table-hover table-sm .table-responsive-sm" , style="width: 800px">
        <thead class="thead-dark filterHead">
        <tr>
          <th scope="co1" class="col-auto filterRow">Идентификатор</th>
          <th scope="col" class="col-auto filterRow">Адрес</th>
          <th scope="col" class="col-auto filterRow">Заказазчик</th>
          <th scope="col" class="col-auto filterRow">Статус</th>
          <th scope="col" class="col-auto filterRow">Дата начала</th>
          <th scope="col" class="col-auto filterRow">Дата завершения</th>
          <th scope="col" class="col-auto filterRow">Будет выполнен</th>
          <th scope="col" class="col-auto filterRow">О грузе</th>
          <th scope="col" class="col-auto filterRow">Комментарий</th>
          <th scope="col" class="col-auto filterRow">Статус</th>
          <th scope="col" class="col-auto filterRow">Водитель</th>
          <th scope="col" class="col-auto filterRow">Вложение</th>
          <th scope="col" class="col-auto filterRow">Действия</th>
        </tr>
        </thead>
        <tbody>
        <%= will_paginate %>
        <% @orders.each do |order| %>
          <tr>
            <td><%= order.id %></td>
            <td style="word-wrap:break-word;min-width: 160px;max-width: 160px;"><%= order.address %></td>
            <td><%= order.user.email %></td>
            <td><%#= order.user.email %> Статус</td>
            <td><%= order.start_date.strftime("%T, %B %d") %></td>
            <td><%= order.end_date.strftime("%T, %B %d") %></td>
            <% if order.work_date != nil %>
              <td><%= order.work_date.strftime("%T, %B %d") %></td>
            <% else %>
              <td>Не назначено</td>
            <% end %>
            <td><%= '666 коробок' %></td>
            <td class="text"><span><%= raw order.comment %></span></td>
            <td><%= 'Новая заявка' %></td>
            <td><%= 'Водитель' %></td>
            <td>
            <td>
              <li><%= link_to 'Show', order %></li>
              <li><%= link_to 'Edit', edit_order_path(order) %></li>
              <li><%= link_to 'Destroy', order, method: :delete, data: {confirm: 'Запись будет удалена.\n Продолжить?'} %> </li>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>
      <div class="pagination">
        <%= will_paginate @orders %>
      </div>
    </div>
    <br>
  </div>
  <div class="com-md-2">
  </div>
  <%= link_to 'New Order', new_order_path %>
</div>

app/views/orders/new.html.erb
<h1>New Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Back', orders_path %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>