config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  resources :orders

  resources :locations


  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :contacts
  resources :contractors
  resources :cars
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/adv_option.rb
class AdvOption < ApplicationRecord
  has_and_belongs_to_many :orders
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car.rb
class Car < ApplicationRecord
  # has_many :driver_appointments
  # has_many :drivers, :through => :driver_appointments
  # has_one :driver
  validates :name, presence: true

  # rails_admin do
  #   configure :driver do
  #     label 'Водитель: '
  #   end
  # end


end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :contractor
  validates :name, presence: true

  rails_admin do
    configure :contractor do
      label 'Контрагент: '
    end
  end
end

app/models/contractor.rb
class Contractor < ApplicationRecord
  has_many :contacts
end

app/models/driver.rb
class Driver < ApplicationRecord
  # has_many :driver_appointments
  # has_many :cars, :through => :driver_appointments
  # has_one :car

  # rails_admin do
  #   configure :car do
  #     label ': '
  #   end
  # end
end

app/models/location.rb
class Location < ApplicationRecord
  geocoded_by :address       # can also be an IP address
  after_validation :geocode  # auto-fetch coordinates
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :adv_options
  has_many :purposes
  # geocoded_by :full_street_address   # can also be an IP address
  # after_validation :geocode          # auto-fetch coordinates
  #
  #Mounts paperclip image
  has_attached_file :file

  #This validates the type of file uploaded. According to this, only images are allowed.
  # validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
  validates_attachment :file, :content_type => {:content_type => %w(image/jpeg image/jpg image/png application/pdf application/msword application/vnd.openxmlformats-officedocument.wordprocessingml.document)},
                       size: {in: 0..5.megabytes}

end

app/models/purpose.rb
class Purpose < ApplicationRecord
end

app/models/transport_company.rb
class TransportCompany < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :orders
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  def index
    if params[:search].present?
      # @locations = Location.near(params[:search], 50, :order => :distance)
      @locations = Location.near(params[:search], 50)
    else
      @locations = Location.all
    end
  end

  def show
    @location = Location.find(params[:id])
  end

  def new
    @location = Location.new
  end

  def create
    @location = Location.new(allowed_params)
    if @location.save
      redirect_to @location, :notice => "Successfully created location."
    else
      render :new
    end
  end

  def edit
    @location = Location.find(params[:id])
  end

  def update
    @location = Location.find(params[:id])
    if @location.update_attributes(allowed_params)
      redirect_to @location, :notice  => "Successfully updated location."
    else
      render :edit
    end
  end

  def destroy
    @location = Location.find(params[:id])
    @location.destroy

    redirect_to locations_url, :notice => "Successfully destroyed location."
  end

  private

  def allowed_params
    params.require(:location).permit(:id, :address, :latitude, :longitude)
  end
end

app/controllers/order_controller.rb
class OrderController < ApplicationController
  def new
  end

  def list
  end

  def delete
  end

  def update
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    # @orders = Order.all
    # @orders = Order.paginate(page: params[:page], per_page: 2)
    @orders = Order.where(user_id: current_user).paginate(page: params[:page], per_page: 2)

  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)
    @order.user = current_user

    respond_to do |format|
      if @order.save
        flash[:notice] = 'Order was successfully created!'
        format.html {redirect_to @order, notice: 'Order was successfully created.'}
        format.json {render :show, status: :created, location: @order}
        # redirect_to root_path
      else
        flash[:alert] = 'Order was not created!'
        format.html {render :new}
        format.json {render json: @order.errors, status: :unprocessable_entity}
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html {redirect_to @order, notice: 'Order was successfully updated.'}
        format.json {render :show, status: :ok, location: @order}
      else
        format.html {render :edit}
        format.json {render json: @order.errors, status: :unprocessable_entity}
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html {redirect_to orders_url, notice: 'Order was successfully destroyed.'}
      format.json {head :no_content}
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_order
    @order = Order.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def order_params
    params.require(:order).permit(:comment, :address, :start_date, :end_date, :dover, :parking, :heat, :wepay, :big, :sum,:file,)
    # params.fetch(:order,:comment,:address,:start_date,:end_date,:dover,:parking,:heat,:wepay,:big, :sum, {})
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  def index
    @order = Order.new
  end

  def about
    redirect_to "/orders/new"
    # @order = Order.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper


end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/contractors_helper.rb
module ContractorsHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/locations/_form.html.erb
<%= form_for @location do |f| %>
  <p>
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </p>
  <p>
    <%= f.label :latitude %><br />
    <%= f.text_field :latitude %>
  </p>
  <p>
    <%= f.label :longitude %><br />
    <%= f.text_field :longitude %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/locations/edit.html.erb
<%= render 'form' %>
<p>
  <%= link_to "Show", @location %> |
  <%= link_to "View All", locations_path %>
</p>

app/views/locations/index.html.erb
<%= form_tag locations_path, :method => :get do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search Near", :name => nil %>
  </p>
<% end %>

<table>
  <tr>
    <th>Address</th>
    <th>Latitude</th>
    <th>Longitude</th>
  </tr>
  <% for location in @locations %>
    <tr>
      <td><%= location.address %></td>
      <td><%= location.latitude %></td>
      <td><%= location.longitude %></td>
      <td><%= link_to "Show", location %></td>
      <td><%= link_to "Edit", edit_location_path(location) %></td>
      <td><%= link_to "Destroy", location, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Location", new_location_path %></p>

app/views/locations/new.html.erb
<%= render 'form' %>
<p><%= link_to "Back to List", locations_path %></p>

app/views/locations/show.html.erb
<p>
  <strong>Address:</strong>
  <%= @location.address %>
</p>
<p>
  <strong>Latitude:</strong>
  <%= @location.latitude %>
</p>
<p>
  <strong>Longitude:</strong>
  <%= @location.longitude %>
</p>

<%= image_tag "http://maps.google.com/maps/api/staticmap?size=450x300&sensor=false&zoom=16&markers=#{@location.latitude}%2C#{@location.longitude}" %>

<h3>Nearby locations</h3>
<ul>
  <% for location in @location.nearbys(10) %>
    <li><%= link_to location.address, location %> (<%= location.distance.round(2) %> miles)</li>
  <% end %>
</ul>

<p>
  <%= link_to "Edit", edit_location_path(@location) %> |
  <%= link_to "Destroy", @location, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", locations_path %>
</p>